// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Session struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Date   string   `json:"date"`
	Series []Series `json:"series"`
}
